image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/
  
Build_test:
  stage: build
  image: node:12
  script:
    - npm install
    - npm run build
    - npm run test
